[package]
name = "mesquitte-core"
version = "0.1.0"
description = "MQTT v3.1.1/v5.0 library."
authors = [
    "sunj <diablur@gmail.com>",
    "qinxin0720 <qinxin_0720@live.com>",
    "fiekers <fiekersfan@gmail.com>",
]
license = "Apache-2.0"
keywords = ["mqtt", "quic", "network", "async"]
categories = ["network-programming", "asynchronous"]
edition = "2021"
rust-version = "1.80"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["mqtt", "mqtts", "ws", "wss", "quic"]

mqtt = []
mqtts = ["rustls"]
ws = ["async-tungstenite", "futures", "tungstenite"]
wss = ["async-tungstenite", "futures", "tungstenite", "rustls"]
quic = ["s2n-quic"]
rustls = [
    "async-tungstenite?/tokio-rustls-webpki-roots",
    "rustls/aws-lc-rs",
    "rustls-pemfile",
    "tokio-rustls/aws-lc-rs",
]

[dependencies]
ahash = "0.8"
async-tungstenite = { version = "0.28", optional = true, features = [
    "tokio-runtime",
] }
dashmap = "6.1"
flume = { version = "0.11", features = ["async"] }
futures = { version = "0.3", optional = true }
futures-sink = "0.3"
futures-util = "0.3"
hashbrown = "0.14"
log = "0.4"
mqtt-codec-kit = { version = "1.0", path = "../mqtt-codec-kit", features = [
    "v4",
    "v5",
    "tokio-codec",
] }
nanoid = "0.4"
parking_lot = "0.12"
pin-project-lite = "0.2"
rustls = { version = "0.23", default-features = false, optional = true }
rustls-pemfile = { version = "2.1", optional = true }
s2n-quic = { version = "1", optional = true }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-util"] }
tokio-rustls = { version = "0.26", default-features = false, optional = true }
tokio-util = { version = "0.7", features = ["codec"] }
tungstenite = { version = "0.24", optional = true }

[dev-dependencies]
env_logger = "0.11"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
